default:
  image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - Build
  - Unit Tests
  - Deploy

check:
  stage: Build
  tags:
    - archon
  before_script:
    - export RUSTFLAGS="-Cdebuginfo=2 --cfg=tarpaulin -A unused"
    - apt-get update
    - apt-get install gfortran build-essential cmake libhdf5-dev -y
    - rustup component add clippy
  script:
    - cargo check --release --verbose --features full,python,sandbox --color always
    - cargo clippy --features full,python,sandbox -- -D warnings
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /\/doc-/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

unit_tests:
  stage: Unit Tests
  tags:
    - archon
  before_script:
    - apt-get update
    - apt-get install gfortran build-essential cmake libhdf5-dev -y
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall cargo-nextest --secure
  script:
    - cargo nextest run -r -j8 --run-ignored=all --features=full,python,sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /\/doc-/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

coverage:
  stage: Unit Tests
  tags:
    - archon
  before_script:
    - apt-get update
    - apt-get install gfortran build-essential cmake libhdf5-dev -y
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall cargo-nextest --secure
    - cargo install llvm-cov
  script:
    - cargo llvm-cov nextest -r -j8 --features=full,sandbox --cobertura --output-path=target/llvm-cov-target/cobertura.xml
  coverage: '/TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov-target/cobertura.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /\/doc-/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# tarpaulin:
#   stage: Unit Tests
#   tags:
#     - archon
#   coverage: '/^\d+.\d+% coverage/'
#   before_script:
#     - export RUSTFLAGS="-Cdebuginfo=2 --cfg=tarpaulin"
#     - export RUST_TEST_THREADS=8
#     - apt-get update
#     - apt-get install gfortran build-essential cmake libhdf5-dev -y
#   script:
#     - cargo install cargo-tarpaulin
#     - cargo tarpaulin -v -t 3600 --release --workspace --engine llvm --no-dead-code --features full,sandbox --color always
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"
#     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /\/doc-/
#       when: never
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

release_job:
  stage: Deploy
  tags:
    - archon
  image: registry.gitlab.com/gitlab-org/cli:latest
  script:
    - echo "Running release job for $CI_COMMIT_TAG..."
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG created using glab CLI provided by GitLab."
    ref: "$CI_COMMIT_SHA"
    tag_name: "$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG

mkdocs:
  stage: Deploy
  image: python:latest
  script:
    - pip install "mkdocs-material[imaging]"
    - pip install mkdocs-git-revision-date-localized-plugin
    - pip install "mkdocstrings[python]"
    - pip install ruff
    - pip install markdown-katex
    - cd docs
    - mkdocs build --site-dir public
    - cd ..
    - mv docs/public .
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /\/doc-/

pages:
  stage: Deploy
  tags:
    - archon
  variables:
    RUSTDOCFLAGS: --html-in-header katex.html
  before_script:
    - apt-get update
    - apt-get install gfortran build-essential cmake libhdf5-dev -y
  script:
    - cargo doc --no-deps --features full,python,sandbox
    - mv target/doc public/api
    - echo '<meta http-equiv="refresh" content="0; url=qsym2/index.html">' > public/api/index.html
  needs:
    - job: mkdocs
      artifacts: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /\/doc-/
