[package]
name = "qsym2"
version = "0.2.0"
edition = "2021"
authors = ["Bang C. Huynh <bang.cong.huynh@gmail.com>"]
description = "Quantum Symbolic Symmetry - A program to perform symmetry transformation and analysis on wavefunctions."

[dependencies]
approx = "0.5.1"
clap = { version = "3.0.5", features = ["cargo"] }
counter = "0.5.7"
derive_builder = "0.12.0"
divisors = "0.2.1"
env_logger = "0.9.0"
factorial = "0.3.0"
fraction = "0.11.0"
itertools = "0.10.3"
indexmap = { version = "1.9.1", features = ["rayon"] }
log = "0.4.17"
nalgebra = "0.30.1"
ndarray = { version = "0.15.6", features = ["rayon"] }
num = "0.4.0"
num-modular = "0.5.1"
num-ord = "0.1.0"
num-traits = "0.2.15"
ordered-float = "3.2.0"
periodic_table = "0.3.1"
phf = { version = "0.11", features = ["macros"] }
proptest = "1.0.0"
primes = "0.3.0"
rand = "0.8.5"
regex = "1.7.0"
rayon = "1.5.3"

[package.metadata.docs.rs]
rustdoc-args = [
  "--html-in-header",
  ".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
]
