[package]
name = "rustyinspect"
version = "0.1.0"
edition = "2021"
authors = ["Bang C. Huynh <bang.cong.huynh@gmail.com>"]
description = "A program to perform symmetry transformation and analysis on wavefunctions."

[dependencies]
divisors = "0.2.1"
fraction = "0.11.0"
periodic_table = "0.3.1"
nalgebra = "0.30.1"
ndarray = { version = "0.15.6", features = ["rayon"] }
num = "0.4.0"
num-traits = "0.2.15"
approx = "0.5.1"
derive_builder = "0.11.2"
log = "0.4.16"
itertools = "0.10.3"
indexmap = "1.9.1"
env_logger = "0.9.0"
clap = { version = "3.0.5", features = ["cargo"] }

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    ".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
]
