[package]
name = "rustyinspect"
version = "0.1.0"
edition = "2021"
authors = ["Bang C. Huynh <bang.cong.huynh@gmail.com>"]
description = "A program to perform symmetry transformation and analysis on wavefunctions."

[dependencies]
periodic_table = "0.3.1"
nalgebra = "0.30.0"
clap = { version = "3.0.5", features = ["cargo"] }

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
