[package]
name = "qsym2"
version = "0.2.0"
edition = "2021"
authors = ["Bang C. Huynh <bang.cong.huynh@gmail.com>"]
description = "Quantum Symbolic Symmetry - A program to perform symmetry transformation and analysis on wavefunctions."

[dependencies]
anyhow = "1.0.70"
approx = "0.5.1"
bitvec = "1.0.1"
clap = { version = "4.2.4", features = ["cargo"] }
counter = "0.5.7"
derive_builder = "0.12.0"
divisors = "0.2.1"
env_logger = "0.10.0"
factorial = "0.3.0"
fraction = "0.13.1"
itertools = "0.10.3"
indexmap = { version = "1.9.1", features = ["rayon"] }
log = "0.4.17"
log4rs = { version = "1.2.0", features = ["file_appender", "pattern_encoder"] }
nalgebra = "0.32.2"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray_einsum_beta = "0.7.0"
ndarray-linalg = { version = "0.16", features = ["openblas-static"] }
num = "0.4.0"
num-complex = "0.4.3"
num-modular = "0.5.1"
num-ord = "0.1.0"
num-traits = "0.2.15"
ordered-float = "3.2.0"
periodic_table = "0.4.0"
phf = { version = "0.11", features = ["macros"] }
proptest = "1.0.0"
primes = "0.3.0"
rand = "0.8.5"
regex = "1.7.0"
rayon = "1.5.3"

[package.metadata.docs.rs]
rustdoc-args = [
  "--html-in-header",
  ".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
]
