site_name: QSym²
site_url: https://qsym2.dev
repo_name: bangconghuynh/qsym2
repo_url: https://gitlab.com/bangconghuynh/qsym2
copyright: Copyright &copy; 2025 Bang C. Huynh
theme:
  name: material
  logo: assets/logos/qsym2_logo_no_text_no_background.svg
  favicon: assets/logos/qsym2_icon.png
  icon:
    repo: fontawesome/brands/gitlab
  font:
    text: Outfit
    code: Fira Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: qsym2-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: qsym2-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.suggest
markdown_extensions:
  - admonition
  - attr_list
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - search
  - social:
      cards_layout_options:
        color: hsl(169.00, 46.00%, 64.00%)
        background_color: hsl(173.15, 3%, 12%)
        font_family: Outfit
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          inventories:
          - https://docs.python.org/3/objects.inv
          options:
            allow_inspection: false
            find_stubs_package: true
            # ----------
            # DOCSTRINGS
            # ----------
            # Tables are generally too large, lists will fix this.
            docstring_section_style: list
            docstring_options:
              # Discard first line of `__init__` method docstrings,
              # useful when merging such docstrings into their parent class'.
              ignore_init_summary: true
            # ----------------
            # CROSS-REFERENCES
            # ----------------
            # Enable cross-references in signatures.
            signature_crossrefs: true
            # Unwrap actual types from `Annotated` type annotations.
            unwrap_annotated: true
            # -------
            # MEMBERS
            # -------
            # Only render pulic symbols.
            # Show class inherited members.
            inherited_members: true
            # Render auto-generated summaries of attributes, functions, etc.
            # at the start of each symbol's documentation.
            summary: false
            # --------
            # HEADINGS
            # --------
            # For auto-generated pages, one module per page,
            # make the module heading be the H1 heading of the page.
            heading_level: 1
            # Render headings for parameters, making them linkable.
            parameter_headings: true
            # Render headings for type parameters too.
            type_parameter_headings: true
            # Always show the heading for the symbol you render with `::: id`.
            show_root_heading: true
            # Only show the name of the symbols you inject render `::: id`.
            show_root_full_path: false
            # Show the type of symbol (class, function, etc.) in the heading.
            show_symbol_type_heading: true
            # Show the type of symbol (class, function, etc.) in the table of contents.
            show_symbol_type_toc: true
            # ----------
            # SIGNATURES
            # ----------
            # Format code to 80 + 10% margin (Black and Ruff defaults)
            # in signatures and attribute value code blocks.
            # Needs Black/Ruff installed.
            line_length: 80
            # Merge signature and docstring of `__init__` methods
            # into their parent class signature and docstring.
            merge_init_into_class: true
            # Render signatures and attribute values in a separate code block,
            # below the symbol heading.
            separate_signature: true
            # Show type annotations in signatures.
            show_signature_annotations: true
            # Show type parameters in signatures.
            show_signature_type_parameters: true
            # -----
            # OTHER
            # -----
            show_submodules: true
            show_category_heading: true
            show_source: false
            show_if_no_docstring: false

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/bangconghuynh
      name: bangconghuynh on GitLab
    - icon: fontawesome/brands/slack
      link: https://qsym2.slack.com
      name: QSym² workspace on Slack
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-5226-4054
      name: Bang C. Huynh's ORCID
extra_css:
  - stylesheets/card.css
  - stylesheets/elements.css
  - stylesheets/qsym2-light.css
  - stylesheets/qsym2-dark.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
nav:
  - index.md
  - Getting started:
    - getting-started/prerequisites.md
    - getting-started/installation.md
    - getting-started/basic-usage.md
  - Methodologies:
    - methodologies/character-table-generation.md
    - methodologies/external-fields.md
    - methodologies/orbit-based-representation-analysis.md
    - methodologies/magnetic-corepresentations.md
    - methodologies/projective-reps-coreps.md
  - Tutorials:
    - tutorials/benzene.md
    - tutorials/adamantane.md
    - tutorials/bf3.md
  - User guide:
    - user-guide/symmetry-group-detection.md
    - user-guide/molecule-symmetrisation.md
    - user-guide/integral-evaluation.md
    - Representation analysis:
      - user-guide/representation-analysis/basics.md
      - user-guide/representation-analysis/slater-determinants.md
      - user-guide/representation-analysis/multideterminants.md
      - user-guide/representation-analysis/vibrational-coordinates.md
      - user-guide/representation-analysis/electron-densities.md
      - user-guide/representation-analysis/real-space-functions.md
    - Projection:
      - user-guide/projection/basics.md
      - user-guide/projection/slater-determinants.md
      - user-guide/projection/electron-densities.md
  - API documentation: https://qsym2.dev/api
  - Python bindings:
    - python/index.md
    - python/common.md
    - python/basis.md
    - python/integrals.md
    - Representation analysis:
      - python/representation-analysis/slater-determinants.md
      - python/representation-analysis/densities.md
      - python/representation-analysis/vibrational-coordinates.md
      - python/representation-analysis/multideterminants.md
    - Projection:
      - python/projection/slater-determinants.md
      - python/projection/densities.md
  - About:
    - about/authorship.md
    - about/development.md
    - about/license.md
