site_name: QSym²
repo_url: https://gitlab.com/bangconghuynh/qsym2
repo_name: bangconghuynh/qsym2
theme:
  name: material
  logo: assets/logos/qsym2_logo_no_text_no_background.svg
  favicon: assets/logos/qsym2_icon.png
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: qsym2-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      # accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - search.suggest
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
